# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

In [1]:
import numpy as np

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [5]:
arr = np.random.randint(0,20, size = (4,7))
arr_2 = (arr - np.min(arr)) / (np.max(arr) - np.min(arr)) 
print(f'Массив arr:\n {arr}; \nНормальзованный массив arr:\n {arr_2}')
print(np.min(arr), np.max(arr))

Массив arr:
 [[ 2 15 12 13  2  8 18]
 [ 2 14  4 17 17  7  3]
 [ 4 18  8 17 10 11  2]
 [ 3  3  4  4  6 10  2]]; 
Нормальзованный массив arr:
 [[0.     0.8125 0.625  0.6875 0.     0.375  1.    ]
 [0.     0.75   0.125  0.9375 0.9375 0.3125 0.0625]
 [0.125  1.     0.375  0.9375 0.5    0.5625 0.    ]
 [0.0625 0.0625 0.125  0.125  0.25   0.5    0.    ]]
2 18


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [20]:
mat = np.random.randint(0,10, size = (8, 10))
st_axis = mat.sum(axis = 1)
min_st = np.min(st_axis)
arr = mat.sum(axis = 1)
ind = np.where(st_axis == min_st)[0][0]
st = mat[ind, :]
print(f'Исходная матрица:\n {mat} \nМинимальная строка в матрице имеет индекс {ind} и сумму значений {min_st}:\n {st} ')
print(f'Сумма строк:\n {st_axis}')

Исходная матрица:
 [[4 7 8 0 4 6 9 0 6 5]
 [5 7 3 2 2 9 1 9 3 4]
 [6 5 4 9 2 1 3 9 8 9]
 [6 9 0 3 8 6 6 2 4 0]
 [4 0 3 4 1 3 0 4 1 7]
 [8 6 1 8 6 3 9 7 9 1]
 [0 2 1 5 2 0 0 2 7 1]
 [0 1 9 2 3 0 7 8 5 2]] 
Минимальная строка в матрице имеет индекс 6 и сумму значени 20:
 [0 2 1 5 2 0 0 2 7 1] 
Сумма строк:
 [49 45 56 44 27 58 20 37]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [21]:
e_1 = np.random.randint(0, 5, size=(3))
e_2 = np.random.randint(0, 5, size=(3))
r_1 = np.sqrt(np.sum(np.square(e_1 - e_2)))
print(f'Первый ветктор:{e_1}\nВторой ветктор:{e_2}\nЕвклидово расстояние:{r_1}')

Первый ветктор:[2 2 4]
Второй ветктор:[4 1 2]
Евклидово расстояние:3.0


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [22]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]).reshape(3,3)
B = np.array([[3, -1], [2, 1]]).reshape(2,2)
C = np.array([[7, 21], [11, 8], [8, 4]]).reshape(3,2)
A = np.linalg.inv(A) #обратная матрица A
B = np.linalg.inv(B) #обратная матрица B
C = -C 
X = np.dot(A, C)
X = np.dot(X, B)
X

array([[ 1.00000000e+00,  5.32907052e-16],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [23]:
ar_1 = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=str)
ar_2 = np.array((ar_1[1:]),dtype = np.int32)
ar_t = ar_2.copy()
ar_2[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
avg_1=np.mean(ar_2[:, 1])
avg_2=np.mean(ar_2[:, 2])
min_1=np.min(ar_2[:, 1])
min_2=np.min(ar_2[:, 2])
max_1=np.max(ar_2[:, 1])
max_2=np.max(ar_2[:, 2])
med_1=np.median(ar_2[:, 1])
med_2=np.median(ar_2[:, 2])
print(f'Средние значения: {avg_1, avg_2}, минимумы: {min_1, min_2}, максимумы: {max_1, max_2} и медианы: {med_1, med_2}')

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [26]:
q=0.75
ar_lim=ar_t[ar_t[:,1]<=np.quantile(ar_2[:,1], q)]
ar_lim

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [ 43407,     35,      7],
       [498432,     65,     15],
       [370915,      5,      4]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [25]:
num=(ar_2[:,1]==0).sum()
ar_3=np.place(ar_t[:,1], ar_t[:,1] == 0, 1)
print(f'Минимальое продолжительность рецепта измененного массива: {np.min(ar_t)}, Коливчество рецептов равных нулю: {num}')

Минимальое продолжительность рецепта измененного массива: 1, Коливчество рецептов равных нулю: 479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [24]:
print(len(np.unique(ar_1[:,0])))

100001


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
print(f'Количество различных значений ингредиентов: {len(np.unique(ar_t[:,2]))}')
print(np.unique(ar_t[:,2]))

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
print(ar_t[ar_t[:,2] <= 5])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
ar_4 = ar_t[:, 2] / ar_t[:, 1]
print(f'Максимальное значение: {np.max(ar_4)}\n{ar_4}')

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
ar_9 = ar_t[np.argsort(ar_t[:, 1])][-100:, 2]
print(np.average(ar_9))

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
print(ar_t[np.random.randint(ar_t.shape[0], size = 10)])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
p_1 = np.mean(ar_t[:,2])
ar_10 = ar_t[ar_t[:,2]<p_1]
res_1=len(ar_10[:,2])/len(ar_t[:,2])
res_1*100

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
ar_cond=(ar_t[:,1] <= 20) & (ar_t[:,2] <= 5)
ar_simp=ar_t[ar_t[:,1]<=20]
ar_simp_1=ar_simp[ar_simp[:,2]<=5]
ar_add=np.hstack((ar_t, ar_cond[:, np.newaxis]))
ar_add

13. Выведите процент "простых" рецептов в датасете

In [ ]:
print(len(ar_simp_1)*100/len(ar_t))

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [28]:
ar_short=ar_t[ar_t[:,1]<=10]
ar_norm_0=ar_t[ar_t[:,1]>10]
ar_norm=ar_norm_0[ar_norm_0[:,1]<=20]
ar_long=ar_t[ar_t[:,1]>20]
#номера группы в трехмерном массиве ar_fin: ar_short - 0; ar_norm - 1; ar_long - 2.
ar_fin=np.arange(149592).reshape(3,12466,4)
ar_fin[0][:,1:]=ar_short[:12466,:]
ar_fin[0][:,0]=0
ar_fin[1][:,1:]=ar_norm[:12466,:]
ar_fin[1][:,0]=1
ar_fin[2][:,1:]=ar_long[:12466,:]
ar_fin[2][:,0]=2
#в трехмерном массивне  представлено по 12466 рецептов из каждой группы, из-за того, что массив numpy должен быть прямоугольным, а длина наименьшего массива ar_short составляет 12466.
ar_fin

array([[[     0,  94746,     10,      6],
        [     0,  67660,      5,      6],
        [     0, 366174,      7,      9],
        ...,
        [     0, 420725,      5,      3],
        [     0,   4747,      1,      9],
        [     0, 370915,      5,      4]],

       [[     1,  33941,     18,      9],
        [     1, 446597,     15,      5],
        [     1,  74205,     20,      7],
        ...,
        [     1, 230115,     20,      7],
        [     1, 496131,     20,      9],
        [     1, 365818,     20,      6]],

       [[     2, 127244,     60,     16],
        [     2,  23891,     25,      7],
        [     2, 157911,     60,     14],
        ...,
        [     2,  68428,     70,     10],
        [     2, 312995,   1445,      7],
        [     2,  93651,    240,     12]]])

In [29]:
len(ar_norm),len(ar_long),len(ar_short)

(14184, 73350, 12466)